branch-defaults:
  default:
    environment: ptah-env
    group_suffix: null
global:
  application_name: ptah
  default_ec2_keyname: ptah
  default_platform: Python 2.7
  default_region: ap-south-1
  profile: eb-cli
  sc: null
