# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arttype',
            old_name='art_forms',
            new_name='art_form',
        ),
    ]
