# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disctype', models.CharField(blank=True, choices=[('F', 'Flat'), ('P', 'Percentage')], max_length=1, null=True, verbose_name='Discount Type')),
                ('discname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount Name')),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('startdate', models.DateTimeField(null=True, verbose_name='Start Date/Time')),
                ('enddate', models.DateTimeField(null=True, verbose_name='End Date/Time')),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regtype', models.CharField(max_length=100, null=True, verbose_name='Registration Type')),
                ('description', models.TextField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('startdate', models.DateTimeField(null=True, verbose_name='Sale Start Date/Time')),
                ('enddate', models.DateTimeField(null=True, verbose_name='Sale End Date/Time')),
                ('addcharges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100, null=True, verbose_name='Venue Name')),
                ('website', models.URLField(blank=True, null=True)),
                ('address', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('cover_photo', models.ImageField(null=True, upload_to='cards/')),
                ('startdate', models.DateTimeField(null=True, verbose_name='Start Date/Time')),
                ('enddate', models.DateTimeField(null=True, verbose_name='End Date/Time')),
                ('total_seats', models.IntegerField(null=True)),
                ('enable', models.BooleanField(default=False)),
                ('art_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtForm')),
                ('art_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtType', verbose_name='Art Type')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistProfile')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artivities.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artivities.Workshop'),
        ),
        migrations.AddField(
            model_name='discount',
            name='regtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artivities.Registration', verbose_name='Registration Type'),
        ),
    ]
