# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
