# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artivities', '0002_auto_20160920_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='fb_event_link',
            field=models.URLField(blank=True, null=True, verbose_name='FB Event Link'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
