# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('artist_type', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('mobile_no', models.CharField(blank=True, help_text='Please enter mobile number without +91 or 0', max_length=10, null=True)),
                ('about_yourself', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists_avatar/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artists_cover_image/')),
                ('dob', models.DateField(null=True)),
                ('art_forms', models.ManyToManyField(to='art.ArtForm')),
            ],
        ),
    ]
