# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20160921_0021'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='art_forms',
            new_name='art_form',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='art_type',
            field=models.ManyToManyField(to='art.ArtType'),
        ),
    ]
