# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20160921_0021'),
        ('artist', '0002_auto_20160921_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='art_form',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='art_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtForm'),
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='art_type',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='art_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtType', verbose_name='Art Type'),
        ),
    ]
