# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20160921_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='FB Account Link'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='insta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
