# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20161014_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
