# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True, verbose_name='Item Name')),
                ('description', models.TextField(max_length=500, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('item_image', models.ImageField(null=True, upload_to='art_shop/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('artform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtForm', verbose_name='Art Form')),
                ('arttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtType', verbose_name='Art Type')),
                ('is_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistProfile', verbose_name='Artist')),
            ],
        ),
    ]
